### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [sadko4u/far-screamer#1]
Dear @sadko4u, is it possible to compile this app for Windows 7 x64? I am not a developer, but an ordinary user, who is looking for a command line way to filter the sound.

**Comment by sadko4u** [comment]
Hello! Just released the 0.5.4 version with updated makefiles and dependencies.

https://github.com/sadko4u/far-screamer/releases/tag/0.5.4

It builds for me on Windows.

**Comment by sadko4u** [comment]
To build it for windows, you need GCC, GNU Make, Git and basic command line tools.
The overall build instructions are here:
https://github.com/sadko4u/far-screamer?tab=readme-ov-file#building

**Comment by sergeevabc** [comment]
If anyone is able to attach a compiled executable file for Windows here, please do so.
